#!/bin/bash

#executes this file before "make V=s"
CFG_VERSION_FILE=".config"
CFG_VERSION_NUMBER=`cat .config | grep CONFIG_VERSION_NUMBER`
echo $CFG_VERSION_NUMBER

VERSION_PRE_FIX="CONFIG_VERSION_NUMBER="
N_CFG_VERSION_NUMBER="CONFIG_VERSION_NUMBER=\"`date +%y%m%d%H%M`\""
echo $N_CFG_VERSION_NUMBER

CFG_VERSION_NUMBER=${CFG_VERSION_NUMBER//\"/\\\"}
N_CFG_VERSION_NUMBER=${N_CFG_VERSION_NUMBER//\"/\\\"}
echo "s/$CFG_VERSION_NUMBER/$N_CFG_VERSION_NUMBER/g"
sed -i 's/'$CFG_VERSION_NUMBER'/'$N_CFG_VERSION_NUMBER'/g' .config
echo "changing $CFG_VERSION_NUMBER to $N_CFG_VERSION_NUMBER"
